# Use the official Golang image as the base image
FROM golang:1.18-alpine

# Set the Current Working Directory inside the container
WORKDIR /Backend

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o main .

# Expose port 1001 to the outside world
EXPOSE 1001

# Command to run the executable
CMD ["./main"]
